# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "UTILS_NFCORE_RNASTRUCTUROME_PIPELINE"
description: Subworkflow with utility functions specific to the nf-core/rnastructurome pipeline
keywords:
  - utility
  - pipeline
  - initialise
  - rnastructurome
components:
  - UTILS_NFSCHEMA_PLUGIN
  - UTILS_NFCORE_PIPELINE
  - UTILS_NEXTFLOW_PIPELINE
  - completionEmail
  - completionSummary
input:
  - version:
      type: boolean
      description: |
        Display version and exit
  - validate_params:
      type: boolean
      description: |
        Validate parameters against the schema at runtime
  - monochrome_logs:
      type: boolean
      description: |
        Do not use coloured log outputs
  - nextflow_cli_args:
      type: list
      description: |
        List of positional Nextflow CLI args
  - outdir:
      type: string
      description: |
        Output directory where results will be saved
  - input:
      type: string
      description: |
        Path to input samplesheet CSV
output:
  - samplesheet:
      type: channel
      description: |
        Channel containing validated sample metadata and FASTQ paths
  - versions:
      type: channel
      description: |
        Channel containing software versions
authors:
  - "@vicbeg"
maintainers:
  - "@vicbeg"
