lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .gitignore
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - subworkflows/nf-core/utils_nfcore_pipeline/main.nf
    - assets/email_template.html
    - assets/nf-core-rnastructurome_logo_light.png
    - docs/images/nf-core-rnastructurome_logo_light.png
    - docs/images/nf-core-rnastructurome_logo_dark.png
    - .github/workflows/branch.yml
  nextflow_config:
    - params.bowtie_all
    - config_defaults:
        - params.bowtie_all
  schema_params: false
  template_strings:
    - bin/r2dt_colour_svg.py
    - bin/viennarna_colour_svg.py
    - modules/local/r2dt/tests/test_r2dt_colour_svg.py
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: RNAcentral
  description: This pipeline analyses chemical-based high-throughput RNA structure
    probing data
  force: false
  is_nfcore: true
  name: rnastructurome
  org: nf-core
  outdir: .
  version: 1.0.0
