name: samtools_qnames
description: Extract the sorted, unique set of read names (QNAMEs) present in a BAM file
keywords:
  - samtools
  - bam
  - qname
  - dedup
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: BAM file
        pattern: "*.bam"
        ontologies: []
output:
  qnames:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.qnames.txt":
          type: file
          description: Sorted, unique list of read names present in the input BAM
          pattern: "*.qnames.txt"
          ontologies: []
  versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies: []
authors:
  - "@vicbeg"
maintainers:
  - "@vicbeg"
